apod_channel: 971765668221440073
apod_url: https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY
enable_package_management: True
auto_load_extensions: True
auto_load_list: [ ]
time:
  hour: 12
  minute: 00

