APOD_URL: "https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY"
#URL of the nasa api endpoint

DISCORD_TOKEN: "OTk4NzczMTE0MjE1MzM4MDMz.G2vPgP.sZkCjMQ05xr3o_ESkQB-S1BDxp0BoKrDP4JjhM"
#Discord token from developer portal in the form of a string( Ex. "text")

CHANNEL: 971765668221440073
#Discord channle_id in the form of an interger(Ex. 52358934), can be obtained from the use of discord dev tools

TIME:

  #Sets the hour for the bot to make the apod post (uses UTC.)
  HOUR: 12

  #Sets the minute of the hour for the bot to make the apod post (uses UTC.)
  MINUTE: 00

