# Please do not directly edit this config file.
# If you do you risk breaking the bot.
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(levelname)s | %(asctime)s | %(filename)s: %(message)s"
    datefmt: '%d-%m-%Y %H:%M:%S'
  verbose:
    format: "Thread: %(thread)d Level: %(levelname)s Time: %(asctime)s -> %(filename)s: %(message)s"
    datefmt: '%d-%m-%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    filename: ./logs/nasa_bot.log
    mode: a
    formatter: verbose
loggers:
  nasa_bot:
    level: DEBUG
    handlers:
      - console
      - file